### ISSUE TITLE
Issues page is empty.

### ISSUE THREAD

**Issue by MrsTonedOne** [wall-nerds/wallening#1]
The issues page is empty. This seems like a oversight since there is no way this branch doesn't have any issues

**Comment by LemonInTheDark** [comment]
![dance](https://user-images.githubusercontent.com/58055496/167276654-3ffb5093-fc6c-4e55-8307-9485e3a62e3c.gif)

**Comment by Kylerace** [comment]
contrary to popular belief, the wallening is perfect

**Comment by MrsTonedOne** [comment]
Fixed by #2

**Comment by MrsTonedOne** [comment]
>not having a `blame mso` tag

**Comment by LemonInTheDark** [comment]
Solvable problem
