### ISSUE TITLE
Xenomorphs lying down might? render above humans

### ISSUE THREAD

**Issue by LemonInTheDark** [wall-nerds/wallening#103]
Check if this is the case, if it is we might need to throw them on the on_floor plane or whatever

**Comment by CapybaraExtravagante** [comment]
![image](https://user-images.githubusercontent.com/110635252/216202978-cd5f454e-3a10-40d0-aed5-98f38e3e6383.png)
they do not.

**Comment by LemonInTheDark** [comment]
pog
