### ISSUE TITLE
It is trivial to hide objects/people under the top parts of walls

### ISSUE THREAD

**Issue by PKPenguin321** [wall-nerds/wallening#11]
## Round ID:
182795

## Reproduction:

![image](https://user-images.githubusercontent.com/8345184/167278781-55f9778e-1c20-4544-897d-724edd75dec9.png)
![image](https://user-images.githubusercontent.com/8345184/167278783-1d7ec3ce-6288-4f4c-a971-b2576ec7eec0.png)
This negatively impacts gameplay in a very tangible way for the sake of aesthetic
Easy reproduction steps for items:
- Place an item on anything that displaces their sprite to the south, such as a table
- Drag the item to a wall

**Comment by PKPenguin321** [comment]
A pretty terrible natural example of this
![image](https://user-images.githubusercontent.com/8345184/167279036-9db90496-d712-4d04-a0f2-1e85ef9ae587.png)
Also the overlay of the alcohol vending machine is not obscured properly

**Comment by LemonInTheDark** [comment]
Potentially reduced by use of pixel shifting? we'll have to see. may need to do work to make the wall mask better

**Comment by LemonInTheDark** [comment]
Frill extended, mostly fixed. Could make it even taller, we'll see
