### ISSUE TITLE
Directional windows layer under humans when it doesn't make sense, should probably frill as well?

### ISSUE THREAD

**Issue by tralezab** [wall-nerds/wallening#110]
I am on the same tile as a south facing directional window, yet I show as being over it.

![image](https://user-images.githubusercontent.com/40974010/193313840-b762311e-14a0-4be4-982f-20442266995b.png)

**Comment by LemonInTheDark** [comment]
The fix for this involves sidemap sin. CLICKTHROUGH tho, that requires the linked pr

**Comment by LemonInTheDark** [comment]
Fixed long ago
