### ISSUE TITLE
Rock walls are fucked up.

### ISSUE THREAD

**Issue by unit0016** [wall-nerds/wallening#130]
Possible duplicate of #102 , but only the frills of rocks are rendering.
![image](https://user-images.githubusercontent.com/50649185/197305805-13c12be2-25ce-4be5-b909-b9c1b3b03cbe.png)

**Comment by LemonInTheDark** [comment]
will be fixed soon, I think it was like a fucked input or something like that, don't exactly recall

**Comment by LemonInTheDark** [comment]
Resolved
