### ISSUE TITLE
Closed Turf Clickin'

### ISSUE THREAD

**Issue by unit0016** [wall-nerds/wallening#132]
Something about the way walls are handled now really fucks with clicking on them. This is most evident in buildmode, but's also applicable trying to weld down a wall or similar.
Area below the red line counts as part of the floor on the tile I'm on:
![image](https://user-images.githubusercontent.com/50649185/197354132-d74a4ae3-5230-4c71-ad43-8576eefddbcd.png)
A rough approximation of where you can click on in buildmode, between two lines:
![image](https://user-images.githubusercontent.com/50649185/197354207-328fe424-816d-428e-984e-a339c6ede6d3.png)

**Comment by LemonInTheDark** [comment]
that's fixable yeah. it's a consequence of how we use overlays. fix is an overlay above walls that catches all clicks

**Comment by unit0016** [comment]
Fixed by #118
