### ISSUE TITLE
Indesctructible "window" turfs are gonna need work.

### ISSUE THREAD

**Issue by unit0016** [wall-nerds/wallening#133]
Asides from just not working at the moment, /turf/closed/indestructible/opsglass (and it's normal window counterpart) aren't set up for the new way windows work, and need special attention.

**Comment by LemonInTheDark** [comment]
I hate admins

**Comment by RimiNosha** [comment]
Might be an idea to make an indestructible helper for use on closed/open turfs/constructs to make them invincible. Though making the indestructible flag work on them might also work. Would require a map update script in either case, though.

**Comment by LemonInTheDark** [comment]
/turf/closed/indestructible does a lot of stuff off proc call, which while possible to move to a flag would be real messy.
We oughta be able to support this it just means applying the window component here, along with something to handle lowwalls

**Comment by LemonInTheDark** [comment]
on reflection, I think a new subtype should be made for this (and maybe doors), maybe off /structure
too much rendering logic (especially IN window smoothing) makes assumptions about how closed turfs will act in game.

**Comment by LemonInTheDark** [comment]
basssically handled, I just copied shit over
