### ISSUE TITLE
Keycard Authenticator needs W/E/S Icons

### ISSUE THREAD

**Issue by unit0016** [wall-nerds/wallening#137]
Keycard auth can only presently fit on a north wall. I gave a crack at come up with sprites for this, but the lights are indented - meaning I hadn't a clue on how to detail that they're flashing on the other two icon states.
Maybe a redesign is in order?

**Comment by axietheaxolotl** [comment]
I'm not entirely sure this is that big of an issue, whilst it is, technically, it's very minor, and we can just map authenticators to only be on north walls. Which is a lot easier/quicker then redesigning the whole sprite for the benefit of directionals.

**Comment by unit0016** [comment]
That feels like an incredibly silly restriction and something that's going to be way more trouble than it's worth when we do a mapping pass, honestly.
