### ISSUE TITLE
Window Smoothing is (Partially) Borked

### ISSUE THREAD

**Issue by unit0016** [wall-nerds/wallening#139]
![image](https://user-images.githubusercontent.com/50649185/198702155-1e15bd2b-9166-4676-b84b-537412a91970.png)
See the left/right sides of both of these. Eek!

**Comment by LemonInTheDark** [comment]
yeah I fucked it. will fix I swear

**Comment by unit0016** [comment]
Doing some additional testing by flying around, I've managed to get the frills of windows to dissapear, too.
![image](https://user-images.githubusercontent.com/50649185/198799673-2cdd33bd-7e40-4fd2-b751-49aa533f024c.png)
Weird! Hopefully the fix'll grab this too.

**Comment by LemonInTheDark** [comment]
that's just reinforced windows not having sprites, fix soon

**Comment by LemonInTheDark** [comment]
![image](https://user-images.githubusercontent.com/58055496/209241770-a1e24930-775a-40fc-9a1b-9efbe7a2416e.png)

both handled
