### ISSUE TITLE
RCD Radial's using a mix of old 32x32 icons and oversized 32x48 icons.

### ISSUE THREAD

**Issue by unit0016** [wall-nerds/wallening#144]
Eek! These might need dedicated icon states like other radials use.
![image](https://user-images.githubusercontent.com/50649185/198801235-e9f6468a-476b-441f-8243-e94b765d4963.png)

**Comment by axietheaxolotl** [comment]
please try and use more informative/descriptive titles when making issues. "silly" doesn't really tell us a whole lot.

**Comment by unit0016** [comment]
![greg16x16](https://user-images.githubusercontent.com/50649185/198840330-dbd8b8ae-e58e-4082-a8f7-d9c8a7d639c3.png)

**Comment by axietheaxolotl** [comment]
~~could easily be fixed if all airlocks were hand-done instead of GAG'd~~

**Comment by unit0016** [comment]
...I get GAGS doesn't provide any proper contrast control, (and that's something that really needs to be looked into - relative greyscale colors would be a swag solution to the problem.) - But I fail to get how GAGS is in any way prohibiting addressing this?

For the record, the way I'd recommend fixing this if anyone beats me to the punch is by making new 24x24(?) icons to match with the other radials. Probably without the 3:4ths perspective to prevent it being a headache. ~~If you're a coderspriter like me the airlock paint/deconstruction icon can probably be retrofitted for the purpose lmao~~

**Comment by unit0016** [comment]
RCD Radial was nuked. This problem might be inherited by the new RCD Menu, but that can be it's own issue.
