### ISSUE TITLE
Wood airlocks need directional states

### ISSUE THREAD

**Issue by LemonInTheDark** [wall-nerds/wallening#155]
![image](https://user-images.githubusercontent.com/58055496/204420188-c5721889-f3bf-453c-be5a-ce2789afa914.png)
bad vibes

**Comment by unit0016** [comment]
What happened here? I swear I saw E/W glass airlocks when I was testing earlier.

**Comment by LemonInTheDark** [comment]
Wait a moment what
there are directional glass ones, but they're not in the /tall airlocks folder for some reason
wood ones are still a fuck tho

**Comment by LemonInTheDark** [comment]
wood ones got handled at... some point?
