### ISSUE TITLE
One-side windows overlap inconsistently depending on what angle they meet at

### ISSUE THREAD

**Issue by PKPenguin321** [wall-nerds/wallening#16]
## Round ID:
182795

## Reproduction:

![image](https://user-images.githubusercontent.com/8345184/167278939-e5ecff95-251f-4b7e-964d-34b2ad36cd87.png)
Notice how some of them overlap, while others appear to not touch each other at all.

**Comment by LemonInTheDark** [comment]
#200 handled this

**Comment by PKPenguin321** [comment]
werk
