### ISSUE TITLE
Making a wall into a grille almost completely obscures any wall-mounted devices that were on it

### ISSUE THREAD

**Issue by PKPenguin321** [wall-nerds/wallening#17]
## Round ID:
182795

## Reproduction:

![image](https://user-images.githubusercontent.com/8345184/167278983-e78437fd-43fa-4129-ab0d-117b4f1ab82b.png)
See if you can spot the door lock button, the camera, the air alarm, the requests console, or the light fixtures in this image

**Comment by LemonInTheDark** [comment]
Wall hangings that are sitting on something that isn't a wall should really break off, but we've not got to that yet

**Comment by LemonInTheDark** [comment]
Fixed by hangings dropping if their wall breaks, thank you arcane
