### ISSUE TITLE
Trim See-Through Breaks with Multi-Z

### ISSUE THREAD

**Issue by unit0016** [wall-nerds/wallening#175]
Spawn yourself on the top floor of a multi-z map, go down a floor. (I used an elevator, personally)
![image](https://user-images.githubusercontent.com/50649185/233814059-ecee3878-9a36-4d22-a180-bf0cf98a23d9.png)
Goofy!

Multi-Z Detail in on high, if it matters.

**Comment by Imaginos16** [comment]
@LemonInTheDark.

A lot of the Multi-Z maps were intentionally ignored because we knew they'd be weird, but this might be worth looking at to see what kind of unexpected behavior is going on.

**Comment by unit0016** [comment]
> A lot of the Multi-Z maps were intentionally ignored because we knew they'd be weird

I can report MINUS this issue, multi-z actually works super grand. Have yet to encounter any weird unexpected behavior and multi-z parallax plays nice with wallening - it's just whatever's going on with the trim seethrough, now.
<details><summary>Unrelated to the actual issue, but it looks VERY fucking nice.</summary>
<p>

![image](https://user-images.githubusercontent.com/50649185/233828224-d82bd5a7-1457-4091-967c-0a170ea9e027.png)

![image](https://user-images.githubusercontent.com/50649185/233828448-ed435590-0108-4857-9c2d-2545a707b18d.png)

![image](https://user-images.githubusercontent.com/50649185/233828451-1c787c20-3216-4e9d-841c-bdb0fb7df23b.png)


</p>
</details>

**Comment by LemonInTheDark** [comment]
> Spawn yourself on the top floor of a multi-z map, go down a floor. (I used an elevator, personally) ![image](https://user-images.githubusercontent.com/50649185/233814059-ecee3878-9a36-4d22-a180-bf0cf98a23d9.png) Goofy!
> 
> Multi-Z Detail in on high, if it matters.

Wut

**Comment by unit0016** [comment]
that's SUPPOSED to be the see-through bit that allows you to peek behind walls/windows when you're next to them.

**Comment by LemonInTheDark** [comment]
> > A lot of the Multi-Z maps were intentionally ignored because we knew they'd be weird
> 
> I can report MINUS this issue, multi-z actually works super grand. Have yet to encounter any weird unexpected behavior and multi-z parallax plays nice with wallening - it's just whatever's going on with the trim seethrough, now.

PLANE CUBEEEE 💪
