### ISSUE TITLE
Firelocks do not play nicely with vertical airlocks

### ISSUE THREAD

**Issue by PKPenguin321** [wall-nerds/wallening#19]
## Round ID:
182795

## Reproduction:

![image](https://user-images.githubusercontent.com/8345184/167279058-7136b990-4989-4337-8d00-2d265f7d333e.png)
Half of the airlock remains visible behind the firelock, while half of the firelock is obscured by the wall below. Visually very noisy and potentially confusing

**Comment by PKPenguin321** [comment]
This is also partially true for horizontal airlocks as well
![image](https://user-images.githubusercontent.com/8345184/167279087-04a024e9-f3e2-4139-9d80-b3b2fd1cc426.png)

**Comment by LemonInTheDark** [comment]
We just like, need new firelock sprites full stop

**Comment by PKPenguin321** [comment]
Closing as it belongs in the megathread for sprites then: https://github.com/wall-nerds/wallening/issues/27
