### ISSUE TITLE
One-side windows should probably not appear to take up a full tile

### ISSUE THREAD

**Issue by PKPenguin321** [wall-nerds/wallening#20]
## Round ID:
182795

## Reproduction:

![image](https://user-images.githubusercontent.com/8345184/167279116-365c98b9-9e0a-467e-bd06-0280c088a72a.png)
The part of the one-side window that appears to be collide-able is at the top of its sprite, while the actual collision is at the bottom. With full-tile walls this is less of an issue because it is a given that the full tile is a collision, but with one-side windows this becomes potentially confusing: In the image above it is not immediately clear that the room is even air-tight.

**Comment by LemonInTheDark** [comment]
I'm a bit unclear on this. Do you think the confusion here is because the other sprites around it aren't 3/4thed so the illusion breaks?

**Comment by PKPenguin321** [comment]
It's that the displacement of where they visually stop and where they will actually stop you is too large. It's not immediately clear where you can stand/where you are stopped, which is an issue with visual clarity. I think this might be helped by maybe making the south-facing sprite a bit shorter.

**Comment by LemonInTheDark** [comment]
You sure?

![image](https://user-images.githubusercontent.com/58055496/167280280-abc2d022-3233-460a-8c0e-00bc14d24278.png)
I think it looks right with mob offsets, sans the horrific cable layer merge thing and transit tubes not matching the style

**Comment by PKPenguin321** [comment]
I suppose this one is subjective. Feel free to close it

**Comment by LemonInTheDark** [comment]
s likely not gonna change
