### ISSUE TITLE
Window frames block lasers

### ISSUE THREAD

**Issue by Capsandi** [wall-nerds/wallening#21]
## Testmerges:

IDK i think it had to do with 3/4ths floors?

## Reproduction:

Shoot at a guy through most glass
shot is blocked by the frame
probably unintended

on master, grilles and windows never eat laser fire, but on the wallening branch these new window frames are blocking every shot from laser guns to laser turrets

**Comment by LemonInTheDark** [comment]
No longer turfs, no longer a problem
