### ISSUE TITLE
Vertical windows blend incorrectly with each other

### ISSUE THREAD

**Issue by PKPenguin321** [wall-nerds/wallening#22]
## Round ID:
182802

## Reproduction:

![image](https://user-images.githubusercontent.com/8345184/167279305-5a4fa7c8-f292-46e1-ae1e-9d2f60db6929.png)
This applies to all vertical lines of windows, but the blast doors underneath the windows in the image above make it much easier to see. Notice the sectioned rectangles of harsh and abrupt color changes.
More examples:
![image](https://user-images.githubusercontent.com/8345184/167279322-92c39269-16bc-4d92-a195-0b63d0019ec0.png)
![image](https://user-images.githubusercontent.com/8345184/167279327-7fd206a9-ed68-4d31-a4cf-5fc44d09f864.png)
![image](https://user-images.githubusercontent.com/8345184/167279331-194c5b61-29ab-4b2e-b770-f34c41f6090d.png)

**Comment by LemonInTheDark** [comment]
We need better smoothing for this yeah

**Comment by LemonInTheDark** [comment]
dealt with long ago
