### ISSUE TITLE
Strange issue with not being able to open lockers/crates next to walls sometimes

### ISSUE THREAD

**Issue by ArcaneMusic** [wall-nerds/wallening#238]
In short:
Cannot open.
![image](https://github.com/wall-nerds/wallening/assets/41715314/1ab6ec93-4caa-46ff-bb39-64a94111438b)

Can open.
![image](https://github.com/wall-nerds/wallening/assets/41715314/f4a1f55c-33f1-47f9-bd43-d17d2d4bd01b)

**Comment by LemonInTheDark** [comment]
is it just the ones below windows?

**Comment by ArcaneMusic** [comment]
It appears to be!
Edit: Or interestingly enough, any north or south tile to a window, but not east or west.

**Comment by LemonInTheDark** [comment]
![image](https://github.com/wall-nerds/wallening/assets/58055496/b1196e89-a5d9-473c-836b-edc1f94b7cc9)
