### ISSUE TITLE
Windoors are placed on the wrong end of tables

### ISSUE THREAD

**Issue by PKPenguin321** [wall-nerds/wallening#24]
## Round ID:
182802

## Reproduction:

![image](https://user-images.githubusercontent.com/8345184/167279371-05878129-3f7e-4c13-b260-19ff321fa65c.png)
This appears to be more of a mapping issue (the windoor should be remapped to the bottom of the table), but it's an issue introduced by the wallening nonetheless.

**Comment by LemonInTheDark** [comment]
I think the issue is more that the windoor should be on the top edge of the table, rather then the bottom edge of the tile above the table.
Might be wrong about that tho

**Comment by LemonInTheDark** [comment]
layering issue that causes this seems to be solved? I blame armhulen
