### ISSUE TITLE
Invisible Grilles & Window Halfsies

### ISSUE THREAD

**Issue by unit0016** [wall-nerds/wallening#256]
![image](https://github.com/user-attachments/assets/b7ac3ac6-09ad-4475-aace-f30f2cbdde8b)

Grilles are invisible when repaired by adding more rods; and windows are sawed in half when dragged from their tile. Relatedly: I can't seem to find a way to construct window frames?

**Comment by LemonInTheDark** [comment]
grills I think have fucked smoothing code? maybe?
window dragging is because the window overlay component does not handle movement properly
window frames should be constructable. idk what's goin on with that.

**Comment by unit0016** [comment]
Checked crafting menu after I couldn't find them in rods or metal sheets; not a clue what's up there.
