### ISSUE TITLE
Wall mounts are supposed to layer on top of wall upper section

### ISSUE THREAD

**Issue by actioninja** [wall-nerds/wallening#26]
![https://i.imgur.com/WCa2EJV.png](https://i.imgur.com/WCa2EJV.png)
![lollll](https://i.imgur.com/Bs5WPlc.png)

I don't have a screen of how it's supposed to look but it's supposed to be on the layer above so it like "hooks" over the top

**Comment by LemonInTheDark** [comment]
Thanks boss

**Comment by LemonInTheDark** [comment]
I think part of this is fire alarms not using the element. Looks right when I put them on the right plane 
![image](https://user-images.githubusercontent.com/58055496/167536931-501d0880-b012-4b8d-970b-3485261a7214.png)
mildly related to #74

**Comment by LemonInTheDark** [comment]
Seems like their element use got lost in a merge
