### ISSUE TITLE
Constructed lights are backwards

### ISSUE THREAD

**Issue by dragomagol** [wall-nerds/wallening#35]
![image](https://user-images.githubusercontent.com/66640614/167280914-b8c6b8e6-b3d8-4107-96d8-c796104d0a80.png)

![image](https://user-images.githubusercontent.com/66640614/167280917-6107a777-24ee-41eb-8088-9c7c4731d0aa.png)

**Comment by PKPenguin321** [comment]
Likely related to https://github.com/wall-nerds/wallening/issues/14

**Comment by dragomagol** [comment]
![image](https://user-images.githubusercontent.com/66640614/167280962-fef501e5-a212-4989-a43c-ba455217314f.png)
