### ISSUE TITLE
Window frames, as closed turfs, block atmos.

### ISSUE THREAD

**Issue by TemporalOroboros** [wall-nerds/wallening#37]
## Testmerges:
THE WALLENING

## Reproduction:
1. Acquire 2 iron sheets.
2. Stack craft a window frame.
3. Start suffocating.

**Comment by LemonInTheDark** [comment]
KYLERRRRRRRRRRRRRRRRRRRRR

**Comment by LemonInTheDark** [comment]
not turfs anymore (thank god)
