### ISSUE TITLE
I'm goku and can fly

### ISSUE THREAD

**Issue by Iamgoofball** [wall-nerds/wallening#44]
https://user-images.githubusercontent.com/4081722/167292072-c77d5811-9cb7-4898-b6bb-5ea9dc4939d4.mp4

**Comment by LemonInTheDark** [comment]
Needs a better name, is this about chairs, or just the offset in general

**Comment by Iamgoofball** [comment]
offset in general

**Comment by LemonInTheDark** [comment]
cope seeth mald (I have a strong feeling it'll feel much better once more things are 3/4th. The door opening for instance feels bad mostly because doors are "too far away" from you)

The chair thing is just a bug tho

**Comment by LemonInTheDark** [comment]
chairs are offset now calling this fixed
