### ISSUE TITLE
Grilles don't have wall fade effect

### ISSUE THREAD

**Issue by Ghilker** [wall-nerds/wallening#46]
![image](https://user-images.githubusercontent.com/42839747/167292542-28ed8309-f718-412b-81aa-58f7f4d8099c.png)

**Comment by LemonInTheDark** [comment]
Not sure if I remember why this was decided on, might need rethinking

**Comment by fippefi** [comment]
They should have wall fade effect and probably render under windows; addt. I recommend making them have low alpha on some bits to begin with due to being a see-through grill in the flat-world

**Comment by LemonInTheDark** [comment]
The window thing is just a mapping/code error, we're changing how grills are used and where, they're not meant to be a part of windows anymore

**Comment by fippefi** [comment]
Aight, then this is separate from #32

**Comment by LemonInTheDark** [comment]
calling this a won't-fix. It is a bit of an issue but I'm ok with it, and it look basically fine enough

**Comment by LemonInTheDark** [comment]
calling this a won't-fix. It is a bit of an issue but I'm ok with it, and it look basically fine enough
