### ISSUE TITLE
Air alarms need their sprites splt for proper emissives

### ISSUE THREAD

**Issue by Zandario** [wall-nerds/wallening#5]
## Info:
Just logging things

## Reproduction:
Look with thine eyes!

![image](https://user-images.githubusercontent.com/34761877/167276807-6d19862e-5304-4071-9e45-57e5a999303e.png)
![image](https://user-images.githubusercontent.com/34761877/167276860-080be12b-1e89-41cc-ac1c-de46c7192d08.png)

**Comment by LemonInTheDark** [comment]
Fixed by https://github.com/wall-nerds/wallening/pull/6

**Comment by LemonInTheDark** [comment]
Thanks tho, you based
