### ISSUE TITLE
Wall objects difficult to find and to interact with

### ISSUE THREAD

**Issue by fippefi** [wall-nerds/wallening#50]
Related but not duplicate of #49,
Generally speaking wall-mounted items are fairly difficult to notice if they are on the west/east walls. Due to station layouts and generally the limited wall-space in rooms, this unfortunately cannot be simply solved by better mapping such as placing majority of items on north/south walls.

Some issues exemplified and annotated below of the Pubbystation Atmos Incinerator room:
![image](https://user-images.githubusercontent.com/5203468/167294978-12af7670-9b79-40f4-870d-99ac454a6b4c.png)
**A:** Airlock controls fairly stealthy (but probably best sprite in the layout visible) Addendum: Airlocks also have old sprites
**B:** Layering issue with ignition button (button below pipe layer for some reason)
**C:** Requests console floating midair
**D:** APC difficult to see, smaller than previous sprite 
**E:** Monitor clipping inside a wall
**F:** Fire Extinguisher locker absolutely tiny
**G:** Fire Alarm and Air Controls almost merged together, difficult to interact with

Feel free to split the issue into multiple subtasks if you feel that'll make for easier tracking.

**Comment by fippefi** [comment]
this is a mapping issue, I pretty much fixed all of these just by doing some mapping.

Should I branch off of experimental or master for fork + PR?

**Comment by Imaginos16** [comment]
> this is a mapping issue, I pretty much fixed all of these just by doing some mapping.
> 
> Should I branch off of experimental or master for fork + PR?

From my understanding, you'd wanna do it all on experimental first before going for the master version.

**Comment by fippefi** [comment]
Aight. StrongDMM ok or Dream Maker, what's the mapping flow here? If you wanna give me the QRD, I'm fippe#0451 on discord as well

**Comment by Imaginos16** [comment]
> Aight. StrongDMM ok or Dream Maker, what's the mapping flow here? If you wanna give me the QRD, I'm fippe#0451 on discord as well

SDMM, preferably join the wallening discord, the invite should be pinned in the tg spriting channel. Hope to see you there!

**Comment by fippefi** [comment]
resolved by #53
