### ISSUE TITLE
ARCANE IS A DOUBLE CHUMBIS and forgot to use the cutter on some totally finished walls.

### ISSUE THREAD

**Issue by ArcaneMusic** [wall-nerds/wallening#56]
Notes from last nights comb over of the wallening test branch: Part 2.

Attached to the wallening trello, we have a few completely finished wall sprites, they were listed as being finished or "in progress" because they were missing low walls I believe, but for the most part my understanding is that they're completely done and we just need to use the cutter on them to get it working.

I'll mirror those sprites here for ease of access.
https://trello.com/b/nGUks73m/walls.
Some highlights:
ROCK WALLS BY INFARED BARON:
![image](https://user-images.githubusercontent.com/41715314/167311474-72f94143-097b-49af-9997-690f5f21dce1.png)
SURVIVAL POD WALLS BY ME:
![image](https://user-images.githubusercontent.com/41715314/167311484-f441255c-a44e-4726-8536-7dbf898ab910.png)
HEIROPHANT WALLS BY KRYSON
![image](https://user-images.githubusercontent.com/41715314/167311510-789f30d4-2bad-42bf-bcc6-c5cfa5e48efb.png)
And mooooore.

**Comment by LemonInTheDark** [comment]
I hate spriters

**Comment by ArcaneMusic** [comment]
Merged and closed
