### ISSUE TITLE
You suffocate while standing on low walls

### ISSUE THREAD

**Issue by dragomagol** [wall-nerds/wallening#63]
![image](https://user-images.githubusercontent.com/66640614/167335159-52d31a4f-9029-44db-ab19-568e7e4461c1.png)

**Comment by LemonInTheDark** [comment]
KYLERRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR

**Comment by CapybaraExtravagante** [comment]
@LemonInTheDark Cannot repro this.

**Comment by LemonInTheDark** [comment]
handled a while back when these were moved from turfs to structs
