### ISSUE TITLE
Blurriness is on the wrong plane(?)

### ISSUE THREAD

**Issue by dragomagol** [wall-nerds/wallening#64]
![image](https://user-images.githubusercontent.com/66640614/167335215-dd01bb99-8e7a-4272-ad35-3a35c1e50c3d.png)

**Comment by LemonInTheDark** [comment]
What?

**Comment by LemonInTheDark** [comment]
![image](https://user-images.githubusercontent.com/58055496/167336059-6521d389-5083-4ee1-93a1-491b98f04805.png)
That's an... interesting effect

**Comment by LemonInTheDark** [comment]
Ah I see yeah I got this. It's cause the wallening stuff hasn't been added to the plane master controllers
