### ISSUE TITLE
See through wall feature is only half a circle

### ISSUE THREAD

**Issue by Comxy** [wall-nerds/wallening#71]
![uhoh](https://user-images.githubusercontent.com/25363960/167505053-e48add69-facc-4099-b85a-4cb6d8235fc2.PNG)
![ohno2](https://user-images.githubusercontent.com/25363960/167505063-b18dff7e-e310-44fc-859e-0fde3a226642.PNG)
When you walk back and forth near a wall you get to see through it, but since it only sees through half a circle it doesn't look smooth.

**Comment by LemonInTheDark** [comment]
related to #3
We really need to come up with a better way of handling this effect

**Comment by dragomagol** [comment]
Can we make it a full circle? or oval?

**Comment by LemonInTheDark** [comment]
We could make it pretty much any shape, so long as you take care with how large it is. Kinda has the lighting overlay problem
