### ISSUE TITLE
South face of windows do not blend with walls correctly

### ISSUE THREAD

**Issue by PKPenguin321** [wall-nerds/wallening#9]
## Round ID:
182795

## Reproduction:

1. Place a window above a wall
2. Behold
![image](https://user-images.githubusercontent.com/8345184/167278617-f33d737f-75e3-4066-9299-61794cc51b28.png)

**Comment by PKPenguin321** [comment]
Another standout example
![image](https://user-images.githubusercontent.com/8345184/167278655-69b7d7d1-1dba-4d2c-bd28-a90394803ec5.png)
If it's not clear why this is bad for some reason it's because it gives the impression that there is empty space between the window and the wall

**Comment by LemonInTheDark** [comment]
We need smoothing code for this yeah, badly.
It's a result of using a non 3/4th tileset, kryson could prob talk more about that

**Comment by LemonInTheDark** [comment]
Handled again long ago
