### ISSUE TITLE
Wall hangings need to be "droppable"

### ISSUE THREAD

**Issue by LemonInTheDark** [wall-nerds/wallening#90]
If something is hanging ON a wall, if you decon the wall that thing should fall off.
This will be quite a lot of work, because a lot of things need to support this in not stupid ways. GOOD LUCK

**Comment by CapybaraExtravagante** [comment]
@LemonInTheDark can you list some edge-cases you're worried about? Is calling destroy on most of these not acceptable? :)

**Comment by san7890** [comment]
We're finally going to handle https://github.com/tgstation/tgstation/issues/22283? Yippie
